language: go
addons:
  apt:
    packages:
    - rpm
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install: env && dep ensure
script: true
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
  - secure: kaB2DYaZLN8BHa1MXi8LsCz83vNyMzKOUxpwyIswUInDivAyT1xXuyVMEj2N5YlHLWV4UEcU3O/7QMndoxPsqX7pYIdKAC6Bd/dynrcVJthk5QDJO0cPg/63XsMgDWiFpA75EttbUCCnFNQgDW41wnF09sKUg2HP7Ca+xIaiRZDBPAq3gxYfdcdSKJeyf8jPhjsOPgk4yjECpxeSbhmrkG6AdAZJTHXtDpPnRNDUgiRYc6Wac2ilyd5UJYl971SBohL824jWLClOG7ipTJvPmOsGs8maUznt9O8zB3u5EnXkKWUs9kf+Ui025qldAPq17YliHE2lZFiqS870KaQwnZe2bRDg27c0Vd21rLRiZaLFMFLwf0l3qaoEJ/jHpWDpwG+Plom8oI32Fp6+DZhV2+jlq0p4vV67w23QCKUsJcPCVgY5COhCOpCR74gxMRtUKcoFc3Mq/kzNMKRDHyprBR2WGPvQU9zh80GqUwkSJ7yzmzzHBCBIXpIHFvvXga0M3z2aCgpGe7CziEE+yI/bt6lDsIreVyzzkHjj3ij/aF2hCmzqPQAKiNkFTE6Hj479vPitaeLyESgrO0rEAwl9dluFuqS1DY2sib1mHP2T4Th7J8oUBnIrDhW8WBJERul3BO8+Cx3iwFZNkvU7nRAsaP0w4kArKc/jsHRsKXAWfIw=
  - secure: s+2LbCwv30Aj/3t93RPwTyrrREb1REKtkTbh3S0x4t/A/sKfTdFK28FEebVV1rQe13z+6KAdl+++OrdtQlSP1ncO/IKZuSqCq7TzCO+Z+mB8kzUltqVZtUuQkotKgfDMissTRmuy2IlsqGjKy3/P2ziZ4DbrQ3Di1pc3KmzNbrYQKIPkAE6rDTX1zBu9PQUhTPQO8SzEAE8nDK+MegW6L0GvPpczMRfCKQRjIUhY/hmpMp1IQJ1TE4BqoeIVfwac+B3lqazjQHRNkBbHP7hcHYRNo9skrG+B0d8X/iFiTMZzp2WdCOGAlrvObYhW9cz+Y3SuWMTRN83bzM+owA4fRuHHjaLRx18mRCVsojEXdcN4GJJZ9SAQ+Y9XGTLGk4dRnbkCoosq9Mg/pEqzr4aplY30D76SMa9CtWXkUsjzszF/04vHMKpXO2sVbh5nIry7rXthyTtxrNmBqI/2Ad7ybRBxG6XQTrFQ0CUAczKk0u1umb6Ram3EcEOmAAM1DWuuogcW8sQxpQHdp99nTp6A/qyIaIhHzUAlbEmDFrx5peuyWRH0fghsxtJNekdpNHpgYOwqz4BZpf6xYdnxqPL4aMbbJZ9ogJkxsX4V/2i4ypqdnVrx8Lt/oSmkKMhRZxsdYbtyZjsPRMQ7ZsCZiujuoAFNvLdykHZ8q4SF5fOI2x0=
  matrix:
    secure: TtwetyxScwvFVu3R0gBlXLGKHiZJkpCu48/FJ4Zqo7zrND0aoGjvJ6jcA8saPwft0N0rD8cDoacXKtYfSh5yx6MT3M3jp8UfVPPxJFwQfhnzm0w4zmmrMrb9KOfhokFaEDcEACZcyLNM5Igb8psvOnbAk3Tui6ohijgHTjXvthIMH1eYEKzRi3JBhMdtoR1d4UqCkIO2EKP5ijWb6rno3yUCgffpmTSL9II4Fxf21havqwMatr3TWfgWjj7tP3arVmCH2MabmsCn+2uFOSRet5pCKPAvCqqjCPrmDac3PDb0ZoF/0IjLb6FnlppO2obXGWdEzQDHsXmxly+NmAc4KDvZmFdH5qPYmrBSTdQywwhN3sPgYyt9j3oASdUIXiMBxRbSnjPF8uwUKUNdIC7PKLK+qCxho8ITNE+UMpbIRUCKkvV8FcKksQGF3NwrsAN7ybeZn2Mw2z/Lnvp8f7Z9UqfYGmwN2VrAICzv38M0ORXloMi3xO2WRsSnPnh+WukZ0SZhUg+1KAjUQmxiG0t2kwFXZUf8pN/a8Jf1GFnw6ViyWrTAzQmAvPR7/KSLVIVYgtGzKkMDvHVx5HYklP0aBG969dS7YVhQo55k44SZukYH723Ak0nriWjyQhxwCQt5BpKrYhAcbuqnYw48+LD6gIirdjgMPty4FbyVfbR+oXo=
